simpligility technologies inc. presents 

= Maven Repository Provisioner

== Introduction

A tool to provision an artifact and all its transitive dependencies from
a source Maven repository to a target Maven repository.

== Usage


----
java -jar maven-repository-provisioner-*-jar-with-dependencies.jar 
----

== Planned Changes

* logback based logging
* better handling of deployment to already populated repo (avoid republishing 
and errors due to that)
* support for source jars
* support for javadoc jars
* support for non-jar artifacts (might already work)
* logging to file and console
* print of usage on invalid config
* break up code in main class
* clean up and streamline pom
* release to Central Repository

== License

Eclipse Public License - v 1.0

For full text see LICENSE file or http://www.apache.org/licenses/LICENSE-2.0
 
== Building 

Run 

----
mvn clean install
----

and in the target folder you will find the jar-with-dependencies file for using 
the tool.

== Contributions

are very welcome. Send a pull request or report issues on GitHub. Even just a 
spelling fix in the readme or anything else really is a welcome help. 

== Contributors

- Manfred Moser http://www.simpligility.com

