simpligility technologies inc. presents 

= Maven Repository Tools

== Introduction

A tool collection of tools to work with Maven repositories.

Maven Repository Provisioner::  a command line tool to provision an artifact 
and all its transitive dependencies from a source Maven repository to a target 
Maven repository.

Repository Provisioner Maven Plugin:: a maven plugin for the same task.. tbd

== Planned Changes

* logback based logging
* better handling of deployment to already populated repo (avoid republishing 
and errors due to that)
* support for source jars
* support for javadoc jars
* support for non-jar artifacts (might already work)
* logging to file and console
* print of usage on invalid config
* break up code in main class
* clean up and streamline pom
* release to Central Repository
* refactor to use same idea/codebase in a repository-provision-maven-plugin maybe

== License

Eclipse Public License - v 1.0

For full text see LICENSE file or http://www.apache.org/licenses/LICENSE-2.0
 
== Building 

Run 

----
mvn clean install
----


== Contributions

are very welcome. Send a pull request or report issues on GitHub. Even just a 
spelling fix in the readme or anything else really is a welcome help. 

== Contributors

- Manfred Moser http://www.simpligility.com

