simpligility technologies inc. presents 

= Maven Repository Tools

== Introduction

A tool collection of tools to work with Maven repositories.

Maven Repository Provisioner::  a command line tool to provision an artifact 
and all its transitive dependencies from a source Maven repository to a target 
Maven repository. See more in the readme file of the module.

Repository Provisioner Maven Plugin:: a maven plugin for the same task.. tbd

== Download

Everything is distributed to the Central Repository:

* Maven Repository Provisioner - download the
+*-jar-with-dependencies.jar+ of the latest version available from
http://repo1.maven.org/maven2/com/simpligility/maven/maven-repository-provisioner/


== Planned Changes

Please check out the https://github.com/simpligility/maven-repository-tools/issues[issues list].

== License

Eclipse Public License - v 1.0

For full text see LICENSE file or https://www.eclipse.org/legal/epl-v10.html
 
== Building 

Run 

----
mvn clean install
----


== Contributions

are very welcome. Send a pull request or report issues on GitHub. Even just a 
spelling fix in the readme or anything else really is a welcome help. 

== Contributors

- Manfred Moser http://www.simpligility.com

