simpligility technologies inc. presents 

= Maven Repository Provisioner

== Introduction

A tool to provision an artifact and all its transitive dependencies from
a source Maven repository to a target Maven repository.

The source repository can be the Central Repository or any other
repository. Typically it can also be the a repository group available
from a repository manager like Sonatype Nexus.

The target repository can be a file-system repository, however
typically it is a repository on a repository manager. The artifacts
are also available for inspection in a temporary local repository
folder. By default it is named +local-repo+.


== Usage

The command 

----
java -jar maven-repository-provisioner-*-jar-with-dependencies.jar 
----

will show full help documentation. A full example invocation
could look like this:

----
java - jar maven-repository-provisioner-*-jar-with-dependencies.jar 
     -a "com.simpligility.maven:progressive-organization-pom:pom:2.3.0"
     -t "http://localhost:8081/nexus/content/repositories/test"
     -u admin
     -p admin123
     -s "http://localhost:8081/nexus/content/groups/public/"
----

See the +test.sh+ script for a number of example invocations.


